CREATE TABLE IF NOT EXISTS static_pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    context VARCHAR(50),
    is_homepage BOOLEAN DEFAULT FALSE,
    content TEXT
);

INSERT INTO static_pages (title, link, context, is_homepage, content) VALUES
('Find Out More', 'budg.local:9999/about', '-', FALSE, '<div class="hero-unit"><h1>Welcome to <br/>abdo alaa application.</h1><p class="description">BUDG Data Governance is our collaborative and shared view of the business. Discover how we depend on each other to deliver, where changes are planned, and how projects are impacted. Trace the lifecycle of information and connect with a broad community of stakeholders with clearly defined responsibilities.</p><p><a href="/search" class="hero-explore"><i class="icon-search4"></i> Explore with Unison &rarr;</a></p>{% if app.user == '' %}<p><a href="/login" class="hero-login openLoginPopup"><i class="icon-reading"></i> Login and start contributing &rarr;</a></p>{% endif %}<p><a href="/about" class="hero-more"><i class="icon-question7"></i> Find out more &rarr;</a></p></div>'),
('Homepage', 'budg.local:9999/home', '-', TRUE, '<div class="hero-unit"><h1>Welcome to <br/>abdo alaa application.</h1><p class="description">BUDG Data Governance is our collaborative and shared view of the business. Discover how we depend on each other to deliver, where changes are planned, and how projects are impacted. Trace the lifecycle of information and connect with a broad community of stakeholders with clearly defined responsibilities.</p><p><a href="/search" class="hero-explore"><i class="icon-search4"></i> Explore with Unison &rarr;</a></p>{% if app.user == '' %}<p><a href="/login" class="hero-login openLoginPopup"><i class="icon-reading"></i> Login and start contributing &rarr;</a></p>{% endif %}<p><a href="/about" class="hero-more"><i class="icon-question7"></i> Find out more &rarr;</a></p></div>'),
('Menu - Interface Tip', 'budg.local:9999/menu-interface-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Regulator Tip', 'budg.local:9999/menu-regulator-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Geography Tip', 'budg.local:9999/menu-geography-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Committee Tip', 'budg.local:9999/menu-committee-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - DataSet Tip', 'budg.local:9999/menu-dataset-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - System Tip', 'budg.local:9999/menu-system-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Glossary Tip', 'budg.local:9999/menu-glossary-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Policy Tip', 'budg.local:9999/menu-policy-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Process Tip', 'budg.local:9999/menu-process-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Project Tip', 'budg.local:9999/menu-project-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Business Tip', 'budg.local:9999/menu-business-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Capability Tip', 'budg.local:9999/menu-capability-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Client Tip', 'budg.local:9999/menu-client-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Legal Entity Tip', 'budg.local:9999/menu-legalentity-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Org Unit Tip', 'budg.local:9999/menu-orgunit-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - People Tip', 'budg.local:9999/menu-people-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Product Tip', 'budg.local:9999/menu-product-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Library Tip', 'budg.local:9999/menu-library-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Regulation Tip', 'budg.local:9999/menu-regulation-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.'),
('Menu - Regulatory Theme Tip', 'budg.local:9999/menu-regulatorytheme-tip', 'menu', FALSE, 'It enables users to manage the content of various pages within BUDG, e.g. Home Page, Help Pages. User must be comfortable with HTML to maintain this.');
