package com.example.budg_v2.model;

import com.google.gson.annotations.SerializedName;
import java.sql.Timestamp;

public class Process {

    @SerializedName("id")
    private Integer id;

    @SerializedName("parentid")
    private Integer parentId;

    @SerializedName("ispublic")
    private Integer isPublic;

    @SerializedName("status")
    private Integer status;

    @SerializedName("statusName")
    private String statusName;

    @SerializedName("type")
    private Integer type;

    @SerializedName("duration_type")
    private Integer durationType;

    @SerializedName("duration")
    private Integer duration;

    @SerializedName("lifecycle_status")
    private Integer lifecycleStatus;

    @SerializedName("processclass_id")
    private Integer processClassId;

    @SerializedName("processautomation_id")
    private Integer processAutomationId;

    @SerializedName("primaryname")
    private String primaryName;

    @SerializedName("refnumber")
    private String refNumber;

    @SerializedName("description")
    private String description;

    @SerializedName("input_description")
    private String inputDescription;

    @SerializedName("output_description")
    private String outputDescription;

    @SerializedName("step_type")
    private Integer stepType;

    @SerializedName("budg_viewing")
    private Integer budgViewing;

    @SerializedName("cancreate")
    private Integer canCreate;

    @SerializedName("canread")
    private Integer canRead;

    @SerializedName("canupdate")
    private Integer canUpdate;

    @SerializedName("candelete")
    private Integer canDelete;

    @SerializedName("canarchive")
    private Integer canArchive;

    @SerializedName("createdatetime")
    private Timestamp createDateTime;

    @SerializedName("lastupdatedatetime")
    private Timestamp lastUpdateDateTime;

    @SerializedName("lastupdateuser_id")
    private Integer lastUpdateUserId;

    @SerializedName("createdby_id")
    private Integer createdById;

    // Segment fields (for segment-based access control and display)
    @SerializedName("segmentId")
    private Integer segmentId;

    @SerializedName("segmentName")
    private String segmentName;

    // Hierarchy-specific fields
    @SerializedName("level")
    private Integer level;

    @SerializedName("path")
    private String path;

    @SerializedName("predecessors")
    private String predecessors;

    @SerializedName("parentName")
    private String parentName;

    @SerializedName("deleteddatetime")
    private Timestamp deletedDateTime;

    @SerializedName("createdByName")
    private String createdByName;

    @SerializedName("lastUpdatedByName")
    private String lastUpdatedByName;

    // Transient field for auto-generated change request ID (not stored in DB)
    @SerializedName("autoGeneratedCRId")
    private transient Integer autoGeneratedCRId;

    public Process() {}

    public Process(Integer id, String primaryName, String description) {
        this.id = id;
        this.primaryName = primaryName;
        this.description = description;
    }

    public Process(String primaryName, String description, Integer parentId) {
        this.primaryName = primaryName;
        this.description = description;
        this.parentId = parentId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Integer getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getDurationType() {
        return durationType;
    }

    public void setDurationType(Integer durationType) {
        this.durationType = durationType;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Integer getLifecycleStatus() {
        return lifecycleStatus;
    }

    public void setLifecycleStatus(Integer lifecycleStatus) {
        this.lifecycleStatus = lifecycleStatus;
    }

    public Integer getProcessClassId() {
        return processClassId;
    }

    public void setProcessClassId(Integer processClassId) {
        this.processClassId = processClassId;
    }

    public Integer getProcessAutomationId() {
        return processAutomationId;
    }

    public void setProcessAutomationId(Integer processAutomationId) {
        this.processAutomationId = processAutomationId;
    }

    public String getPrimaryName() {
        return primaryName;
    }

    public void setPrimaryName(String primaryName) {
        this.primaryName = primaryName;
    }

    public String getRefNumber() {
        return refNumber;
    }

    public void setRefNumber(String refNumber) {
        this.refNumber = refNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getInputDescription() {
        return inputDescription;
    }

    public void setInputDescription(String inputDescription) {
        this.inputDescription = inputDescription;
    }

    public String getOutputDescription() {
        return outputDescription;
    }

    public void setOutputDescription(String outputDescription) {
        this.outputDescription = outputDescription;
    }

    public Integer getStepType() {
        return stepType;
    }

    public void setStepType(Integer stepType) {
        this.stepType = stepType;
    }

    public Integer getBudgViewing() {
        return budgViewing;
    }

    public void setBudgViewing(Integer budgViewing) {
        this.budgViewing = budgViewing;
    }

    public Integer getCanCreate() {
        return canCreate;
    }

    public void setCanCreate(Integer canCreate) {
        this.canCreate = canCreate;
    }

    public Integer getCanRead() {
        return canRead;
    }

    public void setCanRead(Integer canRead) {
        this.canRead = canRead;
    }

    public Integer getCanUpdate() {
        return canUpdate;
    }

    public void setCanUpdate(Integer canUpdate) {
        this.canUpdate = canUpdate;
    }

    public Integer getCanDelete() {
        return canDelete;
    }

    public void setCanDelete(Integer canDelete) {
        this.canDelete = canDelete;
    }

    public Integer getCanArchive() {
        return canArchive;
    }

    public void setCanArchive(Integer canArchive) {
        this.canArchive = canArchive;
    }

    public Timestamp getCreateDateTime() {
        return createDateTime;
    }

    public void setCreateDateTime(Timestamp createDateTime) {
        this.createDateTime = createDateTime;
    }

    public Timestamp getLastUpdateDateTime() {
        return lastUpdateDateTime;
    }

    public void setLastUpdateDateTime(Timestamp lastUpdateDateTime) {
        this.lastUpdateDateTime = lastUpdateDateTime;
    }

    public Integer getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    public void setLastUpdateUserId(Integer lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    public Integer getCreatedById() {
        return createdById;
    }

    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    public Integer getSegmentId() {
        return segmentId;
    }

    public void setSegmentId(Integer segmentId) {
        this.segmentId = segmentId;
    }

    public String getSegmentName() {
        return segmentName;
    }

    public void setSegmentName(String segmentName) {
        this.segmentName = segmentName;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getPredecessors() {
        return predecessors;
    }

    public void setPredecessors(String predecessors) {
        this.predecessors = predecessors;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public Timestamp getDeletedDateTime() {
        return deletedDateTime;
    }

    public void setDeletedDateTime(Timestamp deletedDateTime) {
        this.deletedDateTime = deletedDateTime;
    }

    public String getCreatedByName() {
        return createdByName;
    }

    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    public String getLastUpdatedByName() {
        return lastUpdatedByName;
    }

    public void setLastUpdatedByName(String lastUpdatedByName) {
        this.lastUpdatedByName = lastUpdatedByName;
    }

    // Type name field for hierarchy display
    private String typeName;

    @SerializedName("classificationName")
    private String classificationName;

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getClassificationName() {
        return classificationName;
    }

    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName;
    }

    public Integer getAutoGeneratedCRId() {
        return autoGeneratedCRId;
    }

    public void setAutoGeneratedCRId(Integer autoGeneratedCRId) {
        this.autoGeneratedCRId = autoGeneratedCRId;
    }

    @Override
    public String toString() {
        return "Process{" +
                "id=" + id +
                ", parentId=" + parentId +
                ", isPublic=" + isPublic +
                ", status=" + status +
                ", type=" + type +
                ", durationType=" + durationType +
                ", duration=" + duration +
                ", lifecycleStatus=" + lifecycleStatus +
                ", processClassId=" + processClassId +
                ", processAutomationId=" + processAutomationId +
                ", primaryName='" + primaryName + '\'' +
                ", refNumber='" + refNumber + '\'' +
                ", description='" + description + '\'' +
                ", inputDescription='" + inputDescription + '\'' +
                ", outputDescription='" + outputDescription + '\'' +
                ", stepType='" + stepType + '\'' +
                ", budgViewing=" + budgViewing +
                ", canCreate=" + canCreate +
                ", canRead=" + canRead +
                ", canUpdate=" + canUpdate +
                ", canDelete=" + canDelete +
                ", canArchive=" + canArchive +
                ", createDateTime=" + createDateTime +
                ", lastUpdateDateTime=" + lastUpdateDateTime +
                ", lastUpdateUserId=" + lastUpdateUserId +
                ", deletedDateTime=" + deletedDateTime +
                '}';
    }
}
